### ISSUE TITLE
Allow to parse expressions that are not part of a module

### ISSUE THREAD

**Issue by sol** [haskell-pkg-janitors/haskell-src#1]
It would be awesome if I could parse code snippets.

```
parseExpression :: String -> ParseResult HsExp
```

Would you accept a patch?

**Comment by hvr** [comment]
> Would you accept a patch?

yes!

**Comment by anton-k** [comment]
I would be happy to see it implemented too!

**Comment by andreasabel** [comment]
This issue predates my maintainership.  I close this, but if there is continued interest, please reopen or submit a PR.
