### ISSUE TITLE
Relax constraint on base to allow compilation with ghc 8.10

### ISSUE THREAD

**Issue by andreasabel** [haskell-pkg-janitors/haskell-src#11]
Installation in a fresh ghc 8.10.1 with `cabal install --allow-newer` went fine for me:
```
$ ghc-pkg list haskell-src
...
.../.ghc/x86_64-darwin-8.10.1/package.conf.d
    haskell-src-1.0.3.1
```

**Comment by hvr** [comment]
done; see http://hackage.haskell.org/package/haskell-src-1.0.3.1/revisions/
